### ISSUE TITLE
Create a leaderboard small card for index

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats#114]
We need to create a small leaderboard panel on the index page. 

It should show 10 players, it will be just 1v1, there will be switch for all 4 factions (we could maybe use just the faction icons). 
It should just show columns: rank, elo, alias, streak, ration, total, last game ?? We can test this and see how it looks, maybe we will need to remove some of it out to make it smaller. 

If you want to pick this, feel free to ask for additional questions. 

We can take inspiration from https://aoe4world.com/

<img width="902" alt="image" src="https://user-images.githubusercontent.com/8086995/225265252-0a2dd7ba-f70c-4991-a836-02489380b5c0.png">

**Comment by MarkTallentire** [comment]
This one is actually a bit harder than it looks.

I made a start but there's quite a bit of moving things around to get to here.
I'm not going to claim this and say I'll definitely do it because of my work commitments so if someone wants to pick it up still, feel free. If not I'll try chip away at it.
![image](https://github.com/cohstats/coh3-stats/assets/26217534/0f0ddc57-64a5-4670-8d2d-2356fb34803f)

**Comment by petrvecera** [comment]
@MarkTallentire can you please make a draft MR? I can improve it for you to get the data.
The idea how to get the data:
- The first data are requested via SSR ( server side rendering) 
- When you switch the faction, it would be client side 
 
 Btw if you would like to pick more tasks. I can definitely specify them in much more detail. :) 
 
 Thank you

**Comment by MarkTallentire** [comment]
I think this issue can be closed now?

**Comment by petrvecera** [comment]
Thank you very much 👍
